version: '3.8'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - isaData:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8800:8800" 
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: ""
      DB_NAME: isaData
      PORT: 8800
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

volumes:
  isaData:
    driver: local

networks:
  app-network:
    driver: bridge
