version: '3.8'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - questaoai:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

volumes:
  questaoai:
    driver: local

